FROM bensuperpc/base:latest
MAINTAINER Bensuperpc "bensuperpc@gmail.com"

RUN apt-get update && \
    apt-get -y install \
    libelf-dev \
    libssl-dev \
    libc++-dev \
    clang \
    flang-7 \
    && apt-get clean --yes

RUN update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100 && update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 100

ENV CROSS_TRIPLE x86_64-linux-gnu
ENV CROSS_ROOT /usr/bin
ENV AS=/usr/bin/${CROSS_TRIPLE}-as \
    AR=/usr/bin/${CROSS_TRIPLE}-ar \
    CC=/usr/bin/clang \
    CPP=/usr/bin/clang-cpp \
    CXX=/usr/bin/clang++ \
    LD=/usr/bin/${CROSS_TRIPLE}-ld \
    FC=/usr/bin/${CROSS_TRIPLE}-flang

COPY ${CROSS_TRIPLE}-noop.sh /usr/bin/${CROSS_TRIPLE}-noop

COPY Toolchain.cmake /usr/lib/${CROSS_TRIPLE}/
ENV CMAKE_TOOLCHAIN_FILE /usr/lib/${CROSS_TRIPLE}/Toolchain.cmake

#include "common.label-and-env"
