FROM bensuperpc/base:latest
MAINTAINER Bensuperpc "bensuperpc@gmail.com"

ENV WINEARCH win32
ARG MXE_TARGET_ARCH=i686
ARG MXE_TARGET_THREAD=
ARG MXE_TARGET_LINK=static

#include "common.windows"

#include "common.label-and-env"
